### ISSUE TITLE
User Guide is out of date

### ISSUE THREAD

**Issue by drakumus** [jmquigs/ModelMod#25]
I'm having trouble following the User guide pointed to in the readme and setting up MM with Guild Wars 2.
here: https://github.com/jmquigs/ModelMod/blob/master/Docs/userguide/README.md

Set up steps completed:
- Created a profile and pointed it at Gw2-64.exe
- add the d3d9.dll found in ModelMod-1.1.0.4/bin/modelmod_64 to the bin64 folder in guild wars 2
- Setup Blender and run the setup script
- follow the Start instructions and launch the game

Issues:
- No UI displays ingame for texture selection
- the "Launch Time" config mentioned in the UserGuide is no where to be found in the MM desktop application's UI
- Error in log:
ThreadId(2): Snap confile does not exist: "C:\\snapconfig.yaml"
ThreadId(2): Using defaults
- No snapshots being saved to what is suggested to be the Documents directory of MM: "C:\Users\R\Documents\ModelMod"

**Are there any known issues with having the game on a different drive from MM?**
My install is on D drive but MM is on C drive 
**Can anyone offer any guidance for using this tool with Gw2?**

**Comment by jmquigs** [comment]
Yeah the users guide is a bit wrong now.  You can ignore "Launch Time" that is obsolete.  The snapconfig message is not a problem, you don't need that.  

What input profile are you using in?  For GW2 I suggest the "F keys profile".  Then while in game like on character select, hit ctrl-F6 to clear the texture list then ctrl-F3 or ctrl-F4 to cycle textures.  You should see something on screen turn green-ish (indicating its selected).  If not then something is wrong and I'll probably need the entire log file to debug.

**Comment by drakumus** [comment]
I tried the F key set first and then the other key profile. I didn't notice a green. I'll try again and see if I notice it this time.

**Comment by andyTD2** [comment]
I'm experiencing the same issue as OP. I'm able to see the textures cycling however it won't save any snapshots. I'm assuming the intended directory for saving snapshots is documents/ModelMod. I tested on both 1.1.0.3 and 1.1.0.4 to no avail


Detected root directory (from registry, set by MMLaunch): D:\ModelMod
ThreadId(1): created d3d: 1f60bdca180
ThreadId(1): calling real create device
ThreadId(1): Notice: device being created with D3DCREATE_MULTITHREADED
ThreadId(1): hooking new device: 1f6169ae0c0
ThreadId(1): device vtbl: 1f6169b26b0
ThreadId(1): constant tracking enabled: true
ThreadId(1): hooked device on thread ThreadId(1)
ThreadId(1): created dinput keyboard
ThreadId(2): creating CLR
ThreadId(2): Loading managed dll D:\ModelMod\Bin\TempMMManaged000.dll into CLR
ThreadId(2): using 'd3d9' load context for CLR
ThreadId(2): [M:Interop]: Managed asm: MMManaged, Version=1.1.0.3, Culture=neutral, PublicKeyToken=null
ThreadId(2): [M:Interop]: Initializing managed code
ThreadId(2): OnInitialized called with global state address: 140736404041744
ThreadId(2): [M:ModDBInterop]: exe module: "D:\Guild Wars 2\Gw2-64.exe"
ThreadId(2): [M:State]: Root dir: "D:\ModelMod"
ThreadId(2): [M:State]: Conf: {ProfileKeyName = "Software\ModelMod\Profiles\Profile0000";
 ProfileName = "Gw2-64";
 ExePath = "D:\Guild Wars 2\Gw2-64.exe";
 LoadModsOnStart = true;
 RunModeFull = true;
 InputProfile = "FKeys";
 SnapshotProfile = "Profile1";
 GameProfile = {ReverseNormals = true;
                CommandLineArguments = "";
                DataPathName = "gw2";};
 DocRoot = "C:\Users\A\Documents\ModelMod";
 LaunchWindow = 15;
 MinimumFPS = 28;}
ThreadId(2): [M:Interop]: Init complete, native code: 0 
ThreadId(2): clr initialized
ThreadId(2): mod db load returned: 52
ThreadId(2): created selection texture
ThreadId(3): [M:ModDBInterop]: Async load started
ThreadId(3): [ERROR:M:ModDBInterop]: System.Exception: Data directory does not exist: C:\Users\A\Documents\ModelMod
   at ModelMod.State.get_BaseDataDir@58.Invoke(String message) in M:\ModelMod\MMManaged\State.fs:line 58
   at ModelMod.State.DirLocator.get_BaseDataDir() in M:\ModelMod\MMManaged\State.fs:line 60
   at ModelMod.State.DirLocator.get_ExeDataDir() in M:\ModelMod\MMManaged\State.fs:line 65
   at ModelMod.ModDBInterop.loadFromDataPath() in M:\ModelMod\MMManaged\ModDBInterop.fs:line 112
ThreadId(3): [M:ModDBInterop]: Async load complete
ThreadId(2): mod loading complete
ThreadId(2): unloaded 0 mods
ThreadId(2): using fkey input layout
ThreadId(2): loading snap config
ThreadId(2): Snap confile does not exist: "D:\\snapconfig.yaml"
ThreadId(2): Using defaults
ThreadId(2): loaded snap config: SnapConfig {
  snap_ms: 250
  snap_anim: false
  require gpu: None
  snap_anim_on_count: 1
  vconsts_to_capture: 224
  pconsts_to_capture: 224
  no autosnap meshes
  plugins: None
}

ThreadId(2): loading snap config
ThreadId(2): Snap confile does not exist: "D:\\snapconfig.yaml"
ThreadId(2): Using defaults
ThreadId(2): loaded snap config: SnapConfig {
  snap_ms: 250
  snap_anim: false
  require gpu: None
  snap_anim_on_count: 1
  vconsts_to_capture: 224
  pconsts_to_capture: 224
  no autosnap meshes
  plugins: None
}

ThreadId(2): ending snapshot
ThreadId(2): 1658838415000: 500000 dip calls in 1658838415.10 secs (0.00 dips/sec (fps: 66.95))
ThreadId(2): active texture set contains: 1028 textures
ThreadId(2): ending snapshot
ThreadId(2): ending snapshot
ThreadId(2): ending snapshot
ThreadId(2): ending snapshot
ThreadId(2): ending snapshot
ThreadId(2): ending snapshot
ThreadId(1): device 1f6169ae0c0 refcount is same as internal resource count (1),
                    it is being destroyed: purging resources
ThreadId(1): unloaded 0 mods
ThreadId(1): device released: 1f6169ae0c0, refcount: 0
